language: java

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash) 

before_deploy:
      - git tag v4.0.1
deploy:
  provider: releases
  user: "seregamazur"
  password: "123456789lena"
  file: "BullsAndCows.jar"
  skip_cleanup: true
  on:
    tags: true
